import { Anton, Manrope } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer/Footer";

const anton = Anton({
  variable: "--font-anton",
  subsets: ["latin"],
  weight: "400",
});

const manRope = Manrope({
  variable: "--font-man-rope",
  subsets: ["latin"]
})
export const metadata = {
  title: "Les Petits Plats",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr" className={`${anton.variable} ${manRope.variable}`}>
      <body>
       <main>
        {children}
      </main> 
      <Footer/>
      </body>
    </html>
  );
}
